### ISSUE TITLE
bug(build)#github_token_showed_in_log

### ISSUE THREAD

**Issue by dmike16** [dual-lab/dlab-cli#1]
| Name                       | Description               |
| -------------------------- | --------------------------|
| &#x1F41D;Bug report        | Report a bug in __dlab-cli__ |

# &#x1F41D; bug report

- **Affected package**
  - [ ] cli
  - **bazel**
    - [ ] babel
    - [ ] typescript
    - [ ] react-lib
  - **schematics**
    - [ ] react
    - [ ] angular

- **Expected behavior:**

The github_token file is saved encrypted, but is show **decrypted** on the circleci log. For an open source project is not good. The descypted token **must not be logged**. 

- **Actual behavior:**

  The descrypted token is logged.

- [ ] **Is a regression:**

## &#x1F50E; Minimal Reproduction

See circelci log.

 __link to some repo__

## &#x1F4A3; Exception or Error

```code
```

## &#x1F30F; Your Enviroment

**Tools used**:

```code
```

**Anything else relevant**:

Now the token has been invalidated.  
_Proposal solution_: create a step in config.yml inside the publish job, that store the decrypted token on BASH_ENV

```yml 
 - run:
     name: 'Descrypt github token'
     command: echo 'export GITHUB_TOKEN=$(openssl aes-256-cbc -d -in .circleci/github_token -k ${KEY} -iv ${IV_NONCE})' >> $BASH_ENV
```
